import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Link from "next/link";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div>
      <nav className="border-b p-6">
        <p className="text-4xl font-bold">Metaverse Marketplace</p>
        <div className="flex mt-4">
          <Link href="/" legacyBehavior>
            <a className="mr-6 text-blue-400" style={{fontFamily: "Poppins"}}>
              Home
            </a>
          </Link>
          <Link href="/create-item" legacyBehavior>
            <a className="mr-6 text-blue-400" style={{fontFamily: "Poppins"}}>
              Sell Digital Asset
            </a>
          </Link>
          <Link href="/my-assets" legacyBehavior>
            <a className="mr-6 text-blue-400" style={{fontFamily: "Poppins"}}>
              My Digital Assets
            </a>
          </Link>
          <Link href="/creator-dashboard" legacyBehavior>
            <a className="mr-6 text-blue-400" style={{fontFamily: "Poppins"}}>
              Creator Dashboard
            </a>
          </Link>
        </div>
      </nav>
    </div>
        {children}
      </body>
    </html>
  );
}
